version: 2
jobs:
  MAKE:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: "Code"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            apt-get update
            apt-get update -qq
            apt-get install -qq parted -y
            apt-get install -qq lcov -y
            apt-get install -qq cloc -y
            apt-get install -qq pmccabe -y
            apt-get install gcc-4.8
            source setup.sh
            gcc --version
            g++ --version
            ld --version
      - run:
          name: "Build"
          command: make -s -j $(cat /proc/cpuinfo | grep processor | wc -l)

workflows:
    version: 2
    run_ci:
        jobs:
            - MAKE
