name: ubuntu

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install
        run: |
          sudo apt update -qq
          sudo apt install -qq parted -y
          sudo apt install -qq lcov -y
          sudo apt install -qq cloc -y
          sudo apt install -qq pmccabe -y
          source setup.sh
          gcc --version
          g++ --version
          ld --version

      - name: Build
        run: |
          make -s travis -j $(cat /proc/cpuinfo | grep processor | wc -l)

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: simba-build
          path: make/arduino
